/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxímetro;

import es.javiergarbedo.coordinateslib.CoordinatesConverter;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.time.DurationFormatUtils;
import org.apache.commons.validator.routines.CreditCardValidator;

/**
 *
 * @author Francisco A. Reyes
 */
public class Taxímetro extends javax.swing.JFrame {
        
        int numTicket = 0;
        Calendar fechaHoy; 
        final double TARIFA = 0.50;
        

       
    /**
     * Creates new form Taxímetro
     */
    public Taxímetro() {
        initComponents();
        textoTicket.setText("TICKET\n\uFF1D\uFF1D\uFF1D\uFF1D\n\n");
        botonTerminar.setEnabled(false);
        campoTextLatitud.setText("36.6834");
        campoTextLongitud.setText("-5.45");
    }
        
        
          
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEmpezar = new javax.swing.JButton();
        botonTerminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoTicket = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        textoDestino = new javax.swing.JTextField();
        etiqDestino = new javax.swing.JLabel();
        panelGPS = new javax.swing.JPanel();
        etiqLatitud = new javax.swing.JLabel();
        etiqLongitud = new javax.swing.JLabel();
        campoTextLatitud = new javax.swing.JTextField();
        campoTextLongitud = new javax.swing.JTextField();
        etiqLatConver = new javax.swing.JLabel();
        etiqLonConver = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiqPosGPS = new javax.swing.JLabel();
        etiqDatosTrayecto = new javax.swing.JLabel();
        panelMapa = new javax.swing.JPanel();
        mapita = new javax.swing.JLabel();
        etiqMapa = new javax.swing.JLabel();
        campoTextTarjeta = new javax.swing.JTextField();
        etiqTarjeta = new javax.swing.JLabel();
        botonComprobarTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonEmpezar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flag_1_right_green_2_256.png"))); // NOI18N
        botonEmpezar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEmpezar.setBorderPainted(false);
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        botonTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkered-307567_640.png"))); // NOI18N
        botonTerminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonTerminar.setBorderPainted(false);
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        textoTicket.setColumns(20);
        textoTicket.setRows(5);
        jScrollPane1.setViewportView(textoTicket);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        etiqDestino.setText("Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDestino))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDestino))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelGPS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        etiqLatitud.setText("Latitud: ");

        etiqLongitud.setText("Longitud: ");

        campoTextLatitud.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                campoTextLatitudCaretUpdate(evt);
            }
        });
        campoTextLatitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextLatitudActionPerformed(evt);
            }
        });

        campoTextLongitud.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                campoTextLongitudCaretUpdate(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images_1.jpg"))); // NOI18N

        javax.swing.GroupLayout panelGPSLayout = new javax.swing.GroupLayout(panelGPS);
        panelGPS.setLayout(panelGPSLayout);
        panelGPSLayout.setHorizontalGroup(
            panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqLatitud)
                    .addComponent(etiqLongitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGPSLayout.createSequentialGroup()
                        .addComponent(campoTextLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiqLonConver))
                    .addGroup(panelGPSLayout.createSequentialGroup()
                        .addComponent(campoTextLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiqLatConver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34))
        );
        panelGPSLayout.setVerticalGroup(
            panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelGPSLayout.createSequentialGroup()
                        .addGroup(panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiqLatitud)
                            .addComponent(campoTextLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqLatConver))
                        .addGap(18, 18, 18)
                        .addGroup(panelGPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTextLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqLongitud)
                            .addComponent(etiqLonConver))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etiqPosGPS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiqPosGPS.setText("Posición GPS Inicio");

        etiqDatosTrayecto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiqDatosTrayecto.setText("Datos del trayecto");

        panelMapa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapita, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        etiqMapa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiqMapa.setText("Mapa");

        campoTextTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextTarjetaActionPerformed(evt);
            }
        });

        etiqTarjeta.setText("Tarjeta de crédito:");

        botonComprobarTarjeta.setText("Comprobar");
        botonComprobarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGPS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(etiqMapa))
                                .addGap(0, 106, Short.MAX_VALUE))
                            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqTarjeta)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoTextTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonComprobarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqPosGPS)
                            .addComponent(etiqDatosTrayecto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(etiqPosGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqDatosTrayecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(etiqMapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(etiqTarjeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTextTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonComprobarTarjeta))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextTarjetaActionPerformed

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        botonEmpezar.setEnabled(false);
        botonTerminar.setEnabled(true);
        fechaHoy = Calendar.getInstance();
        
        
        textoTicket.setText("TICKET\n\uFF1D\uFF1D\uFF1D\uFF1D\nNº Ticket: " + ++numTicket + "\nFecha: " + fechaHoy.get(Calendar.DAY_OF_MONTH) 
        + "/" + fechaHoy.get(Calendar.MONTH) + "/" + fechaHoy.get(Calendar.YEAR)                  
        + "\n\nHora Bajada de Bandera: " + fechaHoy.get(Calendar.HOUR_OF_DAY) + ":" + fechaHoy.get(Calendar.MINUTE)
        + ":" + fechaHoy.get(Calendar.SECOND));  
        
        //Calcular tiempo en milisengundos
        
        
        //Cambia los siguientes valores por las direciones de origen y destino deseadas
        String origen = campoTextLatitud.getText() + "," + campoTextLongitud.getText();
        String destino = textoDestino.getText();
        //Hay que sustituir los espacios por el carácter %20 para que se
        //  interprete bien la URL que se generará
        destino = destino.replaceAll(" ", "%20");
        //Cambia el nombre [etiqueta] por el nombre de un objeto JLabel (etiqueta) que
        //  has debido colocar antes en el formulario y que será donde se muestre el mapa.
        //  Deja la etiqueta del formulario sin ningún texto en el diseño.
        javax.swing.JLabel jLabelMapa = mapita;
        //Indica aquí el tamaño que desees para el mapa
        int tamHorizontal = 200;
        int tamVertical = 200;
        //Puedes encontrar más información sobre el uso de mapas estáticos de Google Maps aquí:
        //  http://code.google.com/intl/es-ES/apis/maps/documentation/staticmaps/

        //A partir de aquí no hace falta cambiar nada
            try {
            String txtDireccionImagenMapa = "http://maps.google.com/maps/api/staticmap?path="+
                    origen+"|"+destino+"&size="+tamHorizontal+"x"+tamVertical+
                    "&language=ES&sensor=false";
            System.out.println(txtDireccionImagenMapa);
            java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
            java.awt.Image imagenMapa = toolkit.getImage(new java.net.URL(txtDireccionImagenMapa)); 
            jLabelMapa.setIcon(new javax.swing.ImageIcon(imagenMapa));    
        } catch(java.net.MalformedURLException e) {   
            javax.swing.JOptionPane.showMessageDialog(this, "La dirección de imagen indicada no es correcta");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_botonEmpezarActionPerformed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        botonEmpezar.setEnabled(true);
        botonTerminar.setEnabled(false);
        Calendar horaHoy = Calendar.getInstance();
        DateFormat formatoFecha = DateFormat.getTimeInstance(DateFormat.SHORT);
        
        textoTicket.append("\nHora Fin Trayecto: " + horaHoy.get(Calendar.HOUR_OF_DAY) + ":" 
        + horaHoy.get(Calendar.MINUTE) + ":" + horaHoy.get(Calendar.SECOND)); 

        double horaEmpezar = (fechaHoy.get(Calendar.HOUR_OF_DAY)) * 3600000 ;
        double minutoEmpezar = (fechaHoy.get(Calendar.MINUTE)) * 60000;
        double segundoEmpezar = (fechaHoy.get(Calendar.SECOND)) * 1000;
        long totalEmpezar = (long) (horaEmpezar + minutoEmpezar + segundoEmpezar);
        
        
        double horaFin = (horaHoy.get(Calendar.HOUR_OF_DAY)) * 3600000;
        double minutoFin = (horaHoy.get(Calendar.MINUTE)) * 60000;
        double segundoFin = (horaHoy.get(Calendar.SECOND)) * 1000;
        long totalFin = (long) (horaFin + minutoFin + segundoFin);
        
        DurationFormatUtils tiempoTranscurrido = new DurationFormatUtils();
        String formatoDuracion = "HH:mm:ss";
        
        double TarifaXTiempo = 0.5 + (((totalFin - totalEmpezar) / 1000))* (TARIFA/60);
        double IVATarifa = TarifaXTiempo * 0.21;
        double importeTotal = TarifaXTiempo + IVATarifa;
        
        NumberFormat formatoEuros = NumberFormat.getCurrencyInstance(new Locale("es", "ES"));
        
        textoTicket.append("\nDuración Trayecto: " 
        + tiempoTranscurrido.formatPeriod(totalEmpezar, totalFin, formatoDuracion));
        textoTicket.append("\nTarifa por minuto: " + formatoEuros.format(TARIFA) 
        + "\n\nImporte: " + formatoEuros.format(TarifaXTiempo)
        + "\nIVA: " + formatoEuros.format(IVATarifa)
        + "\nImporte Total: " + formatoEuros.format(importeTotal));
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void botonComprobarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobarTarjetaActionPerformed
        CreditCardValidator tarjetaComprobar = new CreditCardValidator();
        String mensajeTarjeta = tarjetaComprobar.isValid(campoTextTarjeta.getText()) ? "Válida" : "No válida";
        JOptionPane.showMessageDialog(this, mensajeTarjeta , "Tarjeta Comprobada", WIDTH);
    }//GEN-LAST:event_botonComprobarTarjetaActionPerformed

    private void campoTextLatitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextLatitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextLatitudActionPerformed

    private void campoTextLatitudCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_campoTextLatitudCaretUpdate
      //Coordenas Ubrique Lat: 36.6834
      CoordinatesConverter convertPosicion = new CoordinatesConverter();
      etiqLatConver.setText(convertPosicion.decimalToDMS(Double.valueOf(campoTextLatitud.getText())));
      

    }//GEN-LAST:event_campoTextLatitudCaretUpdate

    private void campoTextLongitudCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_campoTextLongitudCaretUpdate
      //Coordenas Ubrique Long: -5.45
      CoordinatesConverter convertPosicion2 = new CoordinatesConverter();
      etiqLonConver.setText(convertPosicion2.decimalToDMS(Double.valueOf(campoTextLongitud.getText())));// TODO add your handling code here:
    }//GEN-LAST:event_campoTextLongitudCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taxímetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taxímetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taxímetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taxímetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taxímetro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprobarTarjeta;
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JButton botonTerminar;
    private javax.swing.JTextField campoTextLatitud;
    private javax.swing.JTextField campoTextLongitud;
    private javax.swing.JTextField campoTextTarjeta;
    private javax.swing.JLabel etiqDatosTrayecto;
    private javax.swing.JLabel etiqDestino;
    private javax.swing.JLabel etiqLatConver;
    private javax.swing.JLabel etiqLatitud;
    private javax.swing.JLabel etiqLonConver;
    private javax.swing.JLabel etiqLongitud;
    private javax.swing.JLabel etiqMapa;
    private javax.swing.JLabel etiqPosGPS;
    private javax.swing.JLabel etiqTarjeta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mapita;
    private javax.swing.JPanel panelGPS;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JTextField textoDestino;
    private javax.swing.JTextArea textoTicket;
    // End of variables declaration//GEN-END:variables
}
